from settings.apps import *
from settings.auth import *
from settings.celery import *
from settings.common import *
from settings.database import *
from settings.drf import *
from settings.i18n import *
from settings.logging import *
from settings.mail import *
from settings.middleware import *
from settings.sessions import *
from settings.static import *
from settings.templates import *
